name: aoe3-deck-sorter
channels:
 - defaults
 - conda-forge
dependencies:
 - python == 3.9
 - numpy == 1.23.3
 - pint
 - ipykernel
 - matplotlib
 - pip
 - black == 22.8.0
 - isort
 - flake8
 - pre-commit
 - pytest
 - pip:
    - ahk
